

server:
  port: 8081

spring:
  application:
    name: Emp
  datasource:
    url: jdbc:mysql://localhost:3306/Employee_Record
    username: root
    password: 421605
    driver-class-name: com.mysql.cj.jdbc.Driver
  liquibase:
    enabled: true
    change-log: classpath:src/main/resources/db/changelog/master.xml

  mybatis:
    config-location: classpath:mybatis-config.xml
    mapper-locations: classpath:mapper/*.xml